# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
# See here for details: https://circleci.com/developer/orbs/licensing ss
version: 2.1
description: Fortune Teller 2



executors:
default:
docker:
- image: cimg/base:2022.03
jobs:
fun:
description: have some fun
executor: default
steps:
- checkout
- run:
name: Install Dependencies
command: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y apt-utils
- run:
name: Install Fortune
command: sudo apt-get install -y fortune
- run:
name: Run Fortune
command: /usr/games/fortune
workflows:
fun-workflow:
jobs:
- fun
